# Generated by Django 5.0.3 on 2024-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('booking_date_time', models.DateTimeField(auto_now=True)),
                ('ticket_type', models.CharField(choices=[('VIP', 'vip'), ('ST', 'standard')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
